version: "3"
services:
  server:
    build:
      context: .
    container_name: quiz_app_server
    ports:
      - "8013:8013"
    volumes:
      - .:/go/src/github.com/nekonenene/gin_quiz_app
    env_file: .env
    depends_on:
      - db
    restart: on-failure
  db:
    image: mysql:5.7
    container_name: quiz_app_db
    env_file: .env
    restart: on-failure
