extends:
  - airbnb-base
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
env:
  browser: true
  es6: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - "@typescript-eslint"
rules:
  "@typescript-eslint/indent": ["error", 2]
